# fly.toml app configuration file generated for heinze-oracle on 2026-03-06T09:46:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heinze-oracle'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  ALLOWED_IP = "82.180.151.30"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
